/**
 * Trip export builders (td-8b959f). Load-bearing pins: HTML escaping of every
 * user-influenced string (this document renders in a browser tab), the app
 * deep-link shapes, and the markdown regression pin (additions are additive —
 * the original structural lines survive).
 */
import { describe, expect, it } from "vitest";
import {
  buildTripHtml,
  buildTripMarkdown,
  tripExportFilename,
  type TripExportData,
} from "./trip-export";
import type { Trip, TripStop } from "./trips";

const TRIP: Trip = {
  id: 7,
  user_id: 1,
  name: "Sanibel <Causeway> & 'Ding' Darling",
  start_date: "2026-09-12",
  end_date: "2026-09-13",
  notes: "Check tide charts.",
  created_at: "2026-08-26",
};

const stop = (over: Partial<TripStop>): TripStop => ({
  id: 1,
  trip_id: 7,
  sort_order: 0,
  hotspot_id: null,
  custom_name: "Stop",
  lat: null,
  lon: null,
  google_place_id: null,
  notes: null,
  target_count_at_save: null,
  field_tip: null,
  field_tip_generated_at: null,
  ...over,
});

const HOSTILE = '<img src=x onerror=alert(1)>';

const DATA: TripExportData = {
  trip: TRIP,
  stops: [
    stop({
      id: 1,
      custom_name: "Ding Darling NWR",
      hotspot_id: "L123456",
      lat: 26.44,
      lon: -82.11,
      field_tip: `Work the low tide flats early. ${HOSTILE}`,
      notes: `Gate opens 7am ${HOSTILE}`,
    }),
    stop({ id: 2, custom_name: `Bunche Beach ${HOSTILE}`, lat: 26.47, lon: -81.97 }),
    stop({ id: 3, custom_name: "No-coords stop" }), // no needs-map entry at all
  ],
  counts: new Map([
    [1, 2],
    [2, 1],
  ]),
  species: new Map([
    [
      1,
      [
        { code: "magwar", comName: "Magnolia Warbler" },
        { code: "roysp1", comName: "Royal & <Sandwich> Tern" },
      ],
    ],
    [2, [{ code: "wilplo", comName: "Wilson's Plover" }]],
  ]),
  origin: "https://birds.example.test",
  generatedAt: new Date("2026-08-26T12:00:00Z"),
};

describe("buildTripHtml", () => {
  const html = buildTripHtml(DATA);

  it("PINNED (XSS): every user-influenced string is escaped — no raw markup survives", () => {
    expect(html).not.toContain("<img");
    expect(html).toContain("&lt;img src=x onerror=alert(1)&gt;");
    // trip name in <title> and <h1>
    expect(html).toContain("<title>Sanibel &lt;Causeway&gt; &amp; &#39;Ding&#39; Darling</title>");
    expect(html).toContain("<h1>Sanibel &lt;Causeway&gt; &amp; &#39;Ding&#39; Darling</h1>");
    // species common name with brackets escaped inside its link
    expect(html).toContain("Royal &amp; &lt;Sandwich&gt; Tern");
  });

  it("links back into the app: open-in-app, hotspot stop name, species with encoded returnTo", () => {
    expect(html).toContain('href="https://birds.example.test/trips/7"');
    expect(html).toContain('href="https://birds.example.test/hotspots/L123456"');
    expect(html).toContain(
      'href="https://birds.example.test/species/magwar?returnTo=%2Ftrips%2F7"',
    );
    // non-hotspot stop name is plain text, not a link
    expect(html).toMatch(/<h3>2\. Bunche Beach/);
    expect(html).not.toContain("/hotspots/null");
  });

  it("renders the field tip only where set, and the external eBird link stays", () => {
    expect(html).toContain("Work the low tide flats early.");
    expect((html.match(/class="tip"/g) ?? []).length).toBe(1);
    expect(html).toContain('https://ebird.org/hotspot/L123456');
  });

  it("self-contained: no external asset references", () => {
    expect(html).not.toMatch(/<script/i);
    expect(html).not.toMatch(/<link/i);
    expect(html).toContain("<style>");
  });

  it("a stop with no needs entry renders without a needs section; empty maps render fine", () => {
    expect(html).toMatch(/<h3>3\. No-coords stop<\/h3>/);
    const bare = buildTripHtml({ ...DATA, counts: new Map(), species: new Map() });
    expect(bare).not.toContain("Needs:");
    expect(bare).toContain("<h1>");
  });
});

describe("buildTripMarkdown", () => {
  const md = buildTripMarkdown(DATA);

  it("PINNED (regression): the original structural lines survive the additions", () => {
    expect(md).toContain(`# ${TRIP.name}`);
    expect(md).toContain("**Dates:** ");
    expect(md).toContain("## Stops (3)");
    expect(md).toContain("### 1. ");
    expect(md).toContain("[📍 Map](");
    expect(md).toContain("[Directions](");
    expect(md).toContain("[eBird hotspot](https://ebird.org/hotspot/L123456)");
    expect(md).toContain("[🧭 Navigate all stops](");
    expect(md).toContain("of your needs reported here (last 14 days, ≤16 km)");
    expect(md).toContain("_Generated by birds.gaylon.photos on ");
  });

  it("adds open-in-app, hotspot-linked stop heading, needs links, and the tip", () => {
    expect(md).toContain("[Open in app](https://birds.example.test/trips/7)");
    expect(md).toContain("### 1. [Ding Darling NWR](https://birds.example.test/hotspots/L123456)");
    expect(md).toContain(
      "[Magnolia Warbler](https://birds.example.test/species/magwar?returnTo=%2Ftrips%2F7)",
    );
    expect(md).toContain("> 💡 Work the low tide flats early.");
  });

  it("empty maps (no apiKey) keep the export renderable with no Needs lines", () => {
    const bare = buildTripMarkdown({ ...DATA, counts: new Map(), species: new Map() });
    expect(bare).not.toContain("Needs:");
    expect(bare).toContain("### 3. No-coords stop");
  });
});

describe("tripExportFilename", () => {
  it("slugifies and falls back", () => {
    expect(tripExportFilename("Sanibel — Sept!")).toBe("trip-sanibel-sept.md");
    expect(tripExportFilename("???")).toBe("trip-trip.md");
  });
});

describe("shared mode (public page — no app deep links, neutral labels)", () => {
  const SHARED: TripExportData = { ...DATA, mode: "shared" };
  const html = buildTripHtml(SHARED);
  const md = buildTripMarkdown(SHARED);

  it("PINNED: no app deep links anywhere — the recipient has no login", () => {
    for (const out of [html, md]) {
      expect(out).not.toContain("Open in app");
      expect(out).not.toContain("/hotspots/");
      expect(out).not.toContain("/species/");
    }
    // species names still present, as plain text
    expect(html).toContain("Magnolia Warbler");
    expect(md).toContain("Targets: Magnolia Warbler");
  });

  it("neutral labels replace the personal phrasing", () => {
    for (const out of [html, md]) {
      expect(out).toContain("target species reported here (last 14 days, ≤16 km)");
      expect(out).not.toContain("of your needs");
      expect(out).not.toContain("Needs:");
      expect(out).toContain("Shared from birds.gaylon.photos");
      expect(out).not.toContain("Generated by");
    }
  });

  it("external links survive: eBird hotspot + Google map/route links", () => {
    for (const out of [html, md]) {
      expect(out).toContain("https://ebird.org/hotspot/L123456");
      expect(out).toContain("google.com");
    }
  });

  it("token-safety metas: noindex + no-referrer (owner mode has neither)", () => {
    expect(html).toContain('<meta name="robots" content="noindex">');
    expect(html).toContain('<meta name="referrer" content="no-referrer">');
    const owner = buildTripHtml(DATA);
    expect(owner).not.toContain("noindex");
    expect(owner).not.toContain("no-referrer");
  });

  it("PINNED (XSS, shared variant): hostile strings stay escaped", () => {
    expect(html).not.toContain("<img");
    expect(html).toContain("&lt;img src=x onerror=alert(1)&gt;");
  });
});
