-- Runtime grants for birds_app (migrations run as birds_owner).

GRANT USAGE ON SCHEMA public TO birds_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO birds_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO birds_app;

ALTER DEFAULT PRIVILEGES FOR ROLE birds_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO birds_app;
ALTER DEFAULT PRIVILEGES FOR ROLE birds_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO birds_app;
